### ISSUE TITLE
Uncaught TypeError on initial copy

### ISSUE THREAD

**Issue by hanno2003** [andig/dbcopy#13]
Hi Everyone,

I retrieve the following error, when running dbcopy from volkszaehler docker container:

`/vz/vendor/bin # php ./dbcopy create -c /vz/etc/dbcopy.nas.yaml 
Creating target schema
Creating tables
/vz/vendor/bin # php ./dbcopy copy -c /vz/etc/dbcopy.nas.yaml 
Dropping FK FK_87C331C781257D5D on properties
Dropping FK FK_2BD88468727ACA70 on entities_in_aggregator
Dropping FK FK_2BD88468DD62C21B on entities_in_aggregator
Dropping FK FK_ADF3F36372F5A1AA on data
Dropping FK FK_B77949FF72F5A1AA on aggregate

Fatal error: Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /vz/vendor/andig/dbcopy/src/Command/CopyCommand.php:90
Stack trace:
#0 /vz/vendor/andig/dbcopy/src/Command/CopyCommand.php(90): join(Array, ',')
#1 /vz/vendor/andig/dbcopy/src/Command/CopyCommand.php(223): DatabaseCopy\Command\CopyCommand->copyTable(Object(Doctrine\DBAL\Schema\Table), false)
#2 /vz/vendor/symfony/console/Command/Command.php(298): DatabaseCopy\Command\CopyCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /vz/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /vz/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(DatabaseCopy\Command\CopyCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /vz/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /vz/vendor/andig/dbcopy/dbcopy(36): Symfony\Component\Console\Application->run()
#7 /vz/vendor/bin/dbcopy(120): include('/vz/vendor/andi...')
#8 {main}
  thrown in /vz/vendor/andig/dbcopy/src/Command/CopyCommand.php on line 90
`

As far as I understood, the syntax from join changed from 

`join(Array, ',')`

to

`join(',', Array)`.

Can anyone confirm?

BTW.: My docker containers uses PHP 8.1.9
My previous - working - pi installation PHP 7.3.31

Thanks in advance / Danke im Voraus!

**Comment by hanno2003** [comment]
no one still active on this repo?
